export const items = [
    { name: "Stone", item_id: "minecraft:stone" },
    { name: "Dirt", item_id: "minecraft:dirt" },
    { name: "Oak Log", item_id: "minecraft:oak_log" },
    { name: "Oak Planks", item_id: "minecraft:oak_planks" },
    { name: "Birch Log", item_id: "minecraft:birch_log" },
    { name: "Birch Planks", item_id: "minecraft:birch_planks" },
    { name: "Spruce Log", item_id: "minecraft:spruce_log" },
    { name: "Spruce Planks", item_id: "minecraft:spruce_planks" },
    { name: "Jungle Log", item_id: "minecraft:jungle_log" },
    { name: "Jungle Planks", item_id: "minecraft:jungle_planks" },
    { name: "Acacia Log", item_id: "minecraft:acacia_log" },
    { name: "Acacia Planks", item_id: "minecraft:acacia_planks" },
    { name: "Warped Stem", item_id: "minecraft:warped_stem" },
    { name: "Warped Planks", item_id: "minecraft:warped_planks" },
    { name: "Dark Oak Log", item_id: "minecraft:dark_oak_log" },
    { name: "Dark Oak Planks", item_id: "minecraft:dark_oak_planks" },
    { name: "Crimson Stem", item_id: "minecraft:crimson_stem" },
    { name: "Crimson Planks", item_id: "minecraft:crimson_planks" },
    { name: "Cobblestone", item_id: "minecraft:cobblestone" },
    { name: "Sand", item_id: "minecraft:sand" },
    { name: "Glass", item_id: "minecraft:glass" },
    { name: "Tinted Glass", item_id: "minecraft:tinted_glass" },
    { name: "Red Stained Glass", item_id: "minecraft:red_stained_glass" },
    { name: "Orange Stained Glass", item_id: "minecraft:orange_stained_glass" },
    { name: "Yellow Stained Glass", item_id: "minecraft:yellow_stained_glass" },
    { name: "Lime Stained Glass", item_id: "minecraft:lime_stained_glass" },
    { name: "Green Stained Glass", item_id: "minecraft:green_stained_glass" },
    { name: "Blue Stained Glass", item_id: "minecraft:blue_stained_glass" },
    { name: "Cyan Stained Glass", item_id: "minecraft:cyan_stained_glass" },
    { name: "Light Blue Stained Glass", item_id: "minecraft:light_blue_stained_glass" },
    { name: "Purple Stained Glass", item_id: "minecraft:purple_stained_glass" },
    { name: "Magenta Stained Glass", item_id: "minecraft:magenta_stained_glass" },
    { name: "Pink Stained Glass", item_id: "minecraft:pink_stained_glass" },
    { name: "Brown Stained Glass", item_id: "minecraft:brown_stained_glass" },
    { name: "Black Stained Glass", item_id: "minecraft:black_stained_glass" },
    { name: "Grey Stained Glass", item_id: "minecraft:grey_stained_glass" },
    { name: "Light Grey Stained Glass", item_id: "minecraft:light_grey_stained_glass" },
    { name: "White Stained Glass", item_id: "minecraft:white_stained_glass" },
    { name: "Iron Ingot", item_id: "minecraft:iron_ingot" },
    { name: "Gold Ingot", item_id: "minecraft:gold_ingot" },
    { name: "Diamond", item_id: "minecraft:diamond" },
    { name: "Coal", item_id: "minecraft:coal" },
];